// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrhUHIuSyZkHENIEkWKFm6LssEqN0TP_c',
    appId: '1:210390775665:web:158b4f590933264e62a8d0',
    messagingSenderId: '210390775665',
    projectId: 'todo-list-897ae',
    authDomain: 'todo-list-897ae.firebaseapp.com',
    storageBucket: 'todo-list-897ae.appspot.com',
    measurementId: 'G-XTYG92BN3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHL-liF5YqN1kL4jUKhkFbmzxlSccYBfA',
    appId: '1:210390775665:android:884fd700840536ab62a8d0',
    messagingSenderId: '210390775665',
    projectId: 'todo-list-897ae',
    storageBucket: 'todo-list-897ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALb_XKREE-KH-kJGlBfHx-kSb9L1E1S6Y',
    appId: '1:210390775665:ios:835e9132c072359b62a8d0',
    messagingSenderId: '210390775665',
    projectId: 'todo-list-897ae',
    storageBucket: 'todo-list-897ae.appspot.com',
    iosBundleId: 'com.example.todoListApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALb_XKREE-KH-kJGlBfHx-kSb9L1E1S6Y',
    appId: '1:210390775665:ios:3f7651ef8f064b0162a8d0',
    messagingSenderId: '210390775665',
    projectId: 'todo-list-897ae',
    storageBucket: 'todo-list-897ae.appspot.com',
    iosBundleId: 'com.example.todoListApplication.RunnerTests',
  );
}
